global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'remote_servers'
    static_configs:
      - targets: ['10.254.2.50:8000', '10.254.2.52:8000']
